language: php
php:
  - '7.0'
  - '7.1'

services:
  - docker

stages:
  - build

before_install:
- docker pull mariadb
- docker pull jeremycurny/php-magento2

jobs:
  include:
    - stage: build
      script: composer install --no-progress
