language: php
php:
  - '7.1'

services:
  - docker

stages:
  - build

before_install:
- docker pull mariadb
- docker pull jeremycurny/php-magento2:7.0-fpm-stretch
- docker pull jeremycurny/php-magento2:7.1-fpm-stretch

jobs:
  include:
    - stage: build
      script: composer install --no-progress
    - stage: test
      script: exit 0
