language: php
php:
  - '7.1'

services:
  - docker

stages:
  - checkstyle
  - build

jobs:
  include:
    - stage: checkstyle
      - script: composer install --no-progress
      - script: vendor/bin/phpcs --standard=MEQP2 --warning-severity=10
    - stage: build
      script: composer install --no-dev --no-progress
    - stage: test
      script: exit 0
