language: php
php:
  - '7.1'

services:
  - docker

stages:
  - checkstyle
  - build

before_install:
  - composer self-update
  - composer global config --auth http-basic.repo.magento.com 6c7c3956d991c6459bcbf6d0d977514f 2319f30adac6169a5c30ad2cb564d177

jobs:
  include:
    - stage: checkstyle
      script: >-
        composer validate;
        composer install --no-progress;
        vendor/bin/phpcs --standard=MEQP2 --warning-severity=10
    - stage: build
      script: composer install --no-dev --no-progress
    - stage: test
      script: exit 0
