language: php
php:
  - '7.1'

services:
  - docker

stages:
  - lint
  - checkstyle
  - build

before_install:
  - composer self-update
  - composer global config --auth http-basic.repo.magento.com 6c7c3956d991c6459bcbf6d0d977514f 2319f30adac6169a5c30ad2cb564d177

install:
  - cd $HOME
  - composer create-project --repository=https://repo.magento.com magento/marketplace-eqp /tmp/magento-coding-standard

jobs:
  include:
    - stage: lint
      script: find . -type f -iregex ".*\.\(php\|phtml\)$" -exec php -l {} \; | (! grep -v "No syntax errors detected")
    - stage: checkstyle
      script: >-
        /tmp/magento-coding-standard/vendor/bin/phpcs . --standard=MEQP2 --extensions=php,phtml
    - stage: build
      script: composer install --no-dev --no-progress
    - stage: test
      script: exit 0
